name: covas-vad
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pip:
      - -r requirements.txt

